### ISSUE TITLE
False alarm when using AFL++ with ASAN

### ISSUE THREAD

**Issue by 5hadowblad3** [AFLplusplus/AFLplusplus#1602]
**Describe the bug**
A false alarm of segmentation fault was raised from ASAN after compiling the libpng release stable version using AFL++4.05a.

**To Reproduce**
Please refer to the details in this [issue](https://sourceforge.net/p/libpng/bugs/300/). I have provided the details of how it can be reproduced with the compiler used and the POC binary and input.

**Comment by vanhauser-thc** [comment]
I cannot reproduce that:
```
$ CC=afl-clang-fast CFLAGS="-fsanitize=address -O0" ./configure --disable-shared
[...]
$ make
[...]
$./pngimage ~/Downloads/pngimage_npd_png_setup_paeth_row2496
$
```
we fixed a few bugs in the instrumentation modules, can you try the newest state from stable or dev?

**Comment by vanhauser-thc** [comment]
that includes doing a `sudo make install` after compilation - otherwise you will be using old afl++ modules.

**Comment by vanhauser-thc** [comment]
I can confirm that that crash you encounter is a bug in the afl++ instrumentation, but as I said that should be fixed.

**Comment by 5hadowblad3** [comment]
Hi, there.

I update the version of AFLplusplus to the newest commit, 3b6fcd911a860a8c.

The problem still exists.

**Comment by vanhauser-thc** [comment]
did you also recompile the target? because that bug resulted in the target being built with the issue.

**Comment by 5hadowblad3** [comment]
Yes. I have recompiled both AFLplusplus and the target from scratch.

**Comment by vanhauser-thc** [comment]
can you please attach a zipped crash input file? I deleted it :(
and can you please link the exact png source you are compiling?

**Comment by vanhauser-thc** [comment]
ah sorry, got it. which libpng version were you compiling?

**Comment by vanhauser-thc** [comment]
I tried again, using libpng version 1.6.40
```
# make
...
SanitizerCoveragePCGUARD++4.06a
[+] Instrumented 111 locations with no collisions (non-hardened, ASAN mode) of which are 0 handled and 0 unhandled selects.
/bin/bash ./libtool  --tag=CC   --mode=link afl-clang-fast  -fsanitize=address -O0   -o timepng contrib/libtests/timepng.o libpng16.la -lm -lz 
libtool: link: afl-clang-fast -fsanitize=address -O0 -o timepng contrib/libtests/timepng.o  ./.libs/libpng16.a -lm -lz
afl-cc++4.06a by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
make[1]: Leaving directory '/prg/test/libpng'
```
but:
```
# ./pngimage pngimage_npd_png_setup_paeth_row2496 
#
```

can you please show the output of ` afl-clang-fast|head -n 2`,   `afl-clang-fast -v` and  `afl-fuzz|head -n 2` ?
and if both show the 4.06a version then in your libpng folder please do a `make clean; make` and try again your crash file.

if this still crashes for you then, then the afl-clang-fast -v output might help ... might be a bug in the llvm version you are using then.

**Comment by 5hadowblad3** [comment]
Here. The libpng version is 1.6.38. I also upload the binary for your reference.
[binaries.zip](https://github.com/AFLplusplus/AFLplusplus/files/10390648/binaries.zip)


For `afl-clang-fast|head -n 2`
~~~~
afl-cc++4.05c by Michal Zalewski, Laszlo Szekeres, Marc Heuse
~~~~

For `afl-clang-fast -v`
~~~~
afl-cc++4.05c by Michal Zalewski, Laszlo Szekeres, Marc Heuse - mode: LLVM-PCGUARD
clang version 11.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
~~~~

For `afl-fuzz|head -n 2`
~~~~
afl-fuzz++4.05c based on afl by Michal Zalewski and a large online community
~~~~

**Comment by vanhauser-thc** [comment]
can you please upgrade the llvm version? e.g. to 14. or anything newer than 11
