### ISSUE TITLE
When I instrument static library and call it in executable binary, afl-showmap shows me wrong result.

### ISSUE THREAD

**Issue by UsQuake** [AFLplusplus/AFLplusplus#1873]
**IMPORTANT**
1. You have verified that the issue to be present in the current `dev` branch.
2. Please supply the command line options and relevant environment variables,
   e.g., a copy-paste of the contents of `out/default/fuzzer_setup`.

Thank you for making AFL++ better!

**Describe the bug**
When I instrument static library with AFL_LLVM_ALLOWLIST and ALLOWLIST is not matched with source directory,
If AFL can't capture any bitmap in instrumented static library, afl-showmap emits error message not the message that "0 bitmaps captured". 
In case of building executable binary directly with afl-clang-fast, afl-showmap emits the message that "0 bitmaps captured", not like static library one's.

**To Reproduce**
1. Clone the AFLplusplus
2. Open *AFLplusplus repository folder* and build. ->`make` , `make install`
3. In *the repository folder*, `ar rcus libafl-rt.a afl-compiler-rt.o`
4. Clone *tiny-js* git **outside** of *the AFLplusplus repository folder*.
5. Set compiler with `export CC=afl-clang-fast` and `export CXX=afl-clang-fast++`.
6. Open cloned *tiny-js* repository folder and `cmake -S . -B build` to make a Makefile & build directory.
7. Open tiny-js/build folder and Instrument static library with `make tiny-js`
8. Copy libafl-rt.a from AFLplusplus repository folder to tiny-js/build folder.
9. Make dummy cpp file to make executable binary to test instrumented static library.
    ``` C++
       // Assume name of this dummy file is lib_test.cpp
       // and this file should be in tiny-js repository folder directly,
       //not in build folder or another sub directory.
       // Compile this dummy code with 
       // clang++ -o lib_test.o -c lib_test.cpp
       // Finally, link object file of this dummy code ,libtiny-js.a and libafl-rt.a.
       // clang++ -o lib_binary lib_test.o -Lpath/to/tiny-js/build -ltiny-js -lafl-rt  
      #include "TinyJS.h"
      #include "TinyJS_Functions.h"
      #include <assert.h>
      #include <stdio.h>
      #include <memory>

      void js_print(CScriptVar *v, void *userdata) {
          printf("> %s\n", v->getParameter("text")->getString().c_str());
      }

      void js_dump(CScriptVar *v, void *userdata) {
          CTinyJS *js = (CTinyJS*)userdata;
          js->root->trace(">  ");
      }


      int main(int argc, char **argv)
      {
        std::shared_ptr<CTinyJS> js = std::make_shared<CTinyJS>();
        /* add the functions from TinyJS_Functions.cpp */
        registerFunctions(js.get());
        /* Add a native function */
        js->addNative("function print(text)", &js_print, 0);
        js->addNative("function dump()", &js_dump, js.get());

        FILE* input_js = fopen("tests/test004.js", "r");
  
        fseek(input_js, 0, SEEK_END);
        const int js_file_size = ftell(input_js);
        rewind(input_js);

        char* code = new char[js_file_size + 1];
        fread(code, 1, js_file_size, input_js);
  
          try {
            js->execute(code);
          } catch (CScriptException *e) {
            printf("ERROR: %s\n", e->text.c_str());
          }
        fclose(input_js);
        delete[] code;
         #ifdef _WIN32
         #ifdef _DEBUG
           _CrtDumpMemoryLeaks();
         #endif
         #endif
        return 0;
      }
   ```

**Expected behavior**

With afl-showmap,
I expect the message that "0 bitmaps captured" not error message

**Screen output/Screenshots**

In case of instrumenting static library and using instrumented library in another executable binary,
result is below..
<img width="1143" alt="tjs_static_1" src="https://github.com/AFLplusplus/AFLplusplus/assets/24998577/b3f173ec-3350-4d2b-83ca-5b417ea9cf83">
<img width="1143" alt="tjs_static_2" src="https://github.com/AFLplusplus/AFLplusplus/assets/24998577/4bd13d36-1dab-4790-abad-78e1926fb922">

**Additional context**

You can say that "Why don't you instrument executable binary source code directly?".
Yes, I know, But I want to instrument only static library, not with shell executable like *d8, jsc,..etc*
Also, I should use partial instrumentation for testing specific features on javascript engines..

**Comment by vanhauser-thc** [comment]
why do you create an .a file? I would just link in the afl-llvm-rt.o file directly?
or use afl-clang-fast for creating lib_binary.
No clue what is going wrong with what you do, but it is an elaborate "I do my own way of fuzzing" that you are pretty much also on your own there with the difficulties that arise out of that decision :)

**Comment by UsQuake** [comment]
I made a libafl-rt.a for instrumenting only javascript engine, with calling Rust FFI from outside of engine. In afl.rs, which is an afl++ instrumentation compiler for rust is using this way to use afl instrumented code. I think this is not important part. because this way is already used in afl.rs. Most of all, Thing that I want to report is that whitelist(allowlist) feature is should be working well in this situation(whether I instrument static libs or  executable binary), but it is not working:( 
If I unset AFL_LLVM_ALLOWLIST, All instrumentation is working as well..
Sorry. Because I'm not good at english, so I think I didn't express my situation as well..
 I can tell you all the situations, If you want.

**Comment by vanhauser-thc** [comment]
I am still not sure I understand :)
but if AFL_LLVM_ALLOWLIST results in no coverage then your list is wrong. maybe the path is not correct etc. so nothing is instrumented in the end.

**Comment by UsQuake** [comment]
Either wrong list is given, I thought bitmap is recognized in afl-showmap like below.
below is result of  running afl-showmap with instrumented binary built in afl-clang-fast and has invalid path in AFL_LLVM_ALLOWLIST 
<img width="918" alt="image_tiny-js" src="https://github.com/AFLplusplus/AFLplusplus/assets/24998577/ddf22d92-67ab-4669-8867-03d2a441dbd6">

**Comment by vanhauser-thc** [comment]
looks like you have a fork server but nothing instrumented. see you anything else than "warning: no instrumentation targets found"?

**Comment by UsQuake** [comment]
Nothing. 

I repeatedly say,

In using AFL_LLVM_WHITELIST feature with INVALID path,
I tried 2 case in below.

Build static library in AFL++, using this library in another executable
which is linked with AFL++ internal object file.
(And this way is working in afl-rs)
-> emit error message that I did not instrument anything,
when I do afl-showmap.

Build executable binary in AFL++ directly
-> emit "Captured 0 tuples" message ,
when I do afl-showmap.

So, I thought one of the two cases was an error.

**Comment by vanhauser-thc** [comment]
It is AFL_LLVM_ALLOWLIST and ..._DENYLIST,  not whitelist.
if you put an invalid path in the ALLOWLIST of course nothing is instrumented. that is obivous.

**Comment by UsQuake** [comment]
Yeah.. But why result of afl-showmap is different in each 2 case?

**Comment by vanhauser-thc** [comment]
I don't get your question, the showmap output is the same
